### PR TITLE
Fix various contract violations

### PR DESCRIPTION
**Pull request by FabAlchemy**
Fixing different runtime errors.

### CODE REVIEW

**Comment by FabAlchemy** [comment]
Hi !
Here is a quick pull request as I'm working with `racket-cord` and encountering some issues.

**Comment by erkin** [comment]
Is there any update on this?

**Comment by FabAlchemy** [comment]
Hi @erkin
I haven't worked on this project for a while, and to be honest I had almost forgotten it 😅
I believe there were some breaking changes in the Discord API, this should be investigated.

Right now, I'm a busy with uni work but I might check it out during the holidays.

**Comment by FabAlchemy** [comment]
@erkin 
Do you have any project or idea in mind?
It might be motivating to know that this work would be useful!

**Comment by erkin** [comment]
@FabAlchemy I'm using this lovely library for the main bot of a fairly large server. It works pretty well but it occasionally crashes with arity mismatch errors. Fortunately it doesn't actually listen to events like channel updates (so the errors are happily ignored). The issue that stands out the most is that it tries to handle `exn:fail:network` unsuccessfully and I can't override it from the bot's end. So it crashes whenever there's a hiccup in the connection, which is fairly regular on my dingy VPS.

**Pull request closed without merging**
